name: Build Android apk 
on: workflow_dispatch
  
jobs:

  build-android-apk:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.2'
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
          
      - name: Clone project
        run: git clone https://github.com/anandnet/Harmony-Music.git

      - name: Flutter doctor
        run: flutter doctor
        
      - name: Install project dependencies
        working-directory: ./Harmony-Music
        run: flutter pub get

      - name: Update lang data
        working-directory: ./Harmony-Music
        run: dart localization/generator.dart

      - name: Set update check flag to true
        working-directory: ./Harmony-Music/lib/utils
        run: echo "const updateCheckFlag = true;" > update_check_flag_file.dart
        
      - name: Build android apk
        working-directory: ./Harmony-Music
        run: |
          flutter build apk --split-per-abi --release
          flutter build apk

      - name: Upload apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: Harmony music apk
          path: ./Harmony-Music/build/app/outputs/flutter-apk/*apk
